### ISSUE TITLE
.svg images not allowed

### ISSUE THREAD

**Issue by LykaiosNZ** [jsreport/jsreport-images#2]
While SVG is a valid type to use for `<img>`, the uploader does not allow .svg files to be uploaded. I added it to the list of allowed extensions myself and it worked perfectly fine with phantom-pdf.

Of course it's possible to create a child template with a `<svg>` but I'd like to give my users the option of doing it the `<img>` way :)

**Comment by pofider** [comment]
It is already possible to upload svg files in the latest release.

Now - https://github.com/jsreport/jsreport-images/commit/6443bac46c6a83fce3354182dd4fdcb72a0290a1 I just fixed a minor bug which was preventing svg files to be displayed in its preview, however it should already work in the templates correctly. The minor fix will be part of the next jsreport hotfix

**Comment by pofider** [comment]
Thank you for the submitted issue. I was not testing svg files before, this was very helpful.

**Comment by mdarkawi** [comment]
Hello 
with docxImage I cannot display svg file with remote url or in base64.
Is it possible at least with remote url?

**Comment by bjrmatos** [comment]
@mdarkawi svg images are not supported for docxImage

**Comment by bjrmatos** [comment]
@mdarkawi i've opened new issue to support svg in docxImage, subscribe [here](https://github.com/jsreport/jsreport/issues/1078) for updates, however it may take a while before we get to it.
