### ISSUE TITLE
Html image render

### ISSUE THREAD

**Issue by magnosfire** [jsreport/jsreport-images#3]
Hi, I am trying to render an imagem using a parameter. And it not working.

`jsreport.init().then(function () {
                        return jsreport.render({
                            template: {
                                filename: results.data.templateName,
                                content: results.data.templateText,
                                engine: 'handlebars',
                                recipe: 'phantom-pdf',
                                phantom: {
                                    "margin": {
                                        "top": "1cm",
                                        "left": "3cm",
                                        "bottom": "1cm",
                                        "right": "3cm"
                                    }
                                }
                            },
                            data: {
                                name: "magnosfire",
                                image: ""<img src='https://www.google.com.br/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'>"
                            }
                        }).then(function (out) {
                            out.stream.pipe(res);
                        }).catch(function (e) {
                            res.end(e.message);
                        })
                    });
                }`

And the result is: < img src='htt ps://www.googl e.com.br/images/branding/googlelogo/2x/googl elogo_color_272x92dp.pn g'>. - Without the blank spaces

Is it normal? How can I render this image inside the report using parameter?

**Comment by pofider** [comment]
Unfortunately, I don't understand your question. 

Maybe you can try it to formulate it differently? Or use playground to replicate the problem?
https://playground.jsreport.net

**Comment by magnosfire** [comment]
Sorry about that. I need put a image in the pdf. However the URL is stored in the database. Then, I get a URL from database, and I fill the data parameter with the picture URL. However, when the pdf is rendered it not show my picture. It show a HTML TAG, with the picture URL.

**Comment by magnosfire** [comment]
I found the solution . It don't work as I expected because first the jsreport render the content, and after that it try find the parameter and substitute with the new information.
jsreport.render process ->
-init,
-render content/html,
-substitute the data.
